app = 'canvas-relay-testnet'
primary_region = 'ewr'
kill_signal = 'SIGINT'
kill_timeout = '30s'

[build]

[env]
ANNOUNCE = '/dns6/canvas-relay-testnet.internal/tcp/8080/ws'
DEBUG = 'libp2p:circuit-relay:*'
LISTEN = '/ip4/0.0.0.0/tcp/8080/ws'
PORT = '8000'

[[services]]
protocol = 'tcp'
internal_port = 8080
processes = ['app']

[services.concurrency]
type = 'connections'
hard_limit = 1024
soft_limit = 512

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1

[[metrics]]
port = 8000
path = '/metrics'
