# fly.toml file generated for canvas-notes on 2023-03-02T17:05:29Z

app = "canvas-notes"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/data"
  source = "canvas_notes_data"

[[services]]
  http_checks = []
  internal_port = 4044
  processes = ["app"]
  protocol = "tcp"
  tcp_checks = []
  [services.concurrency]
    hard_limit = 100
    soft_limit = 100
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 4044

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 100
    soft_limit = 100
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/dist"
  url_prefix = "/"
