app = "canvas-chat-discovery-p0"
kill_signal = "SIGINT"
kill_timeout = 30
processes = []

[[vm]]
  memory = "2gb"

[env]
  BOOTSTRAP_LIST = "/dns6/canvas-chat-discovery-p1.internal/tcp/8080/ws/p2p/12D3KooWNfH4Z4ayppVFyTKv8BBYLLvkR1nfWkjcSTqYdS4gTueq /dns6/canvas-chat-discovery-p2.internal/tcp/8080/ws/p2p/12D3KooWRBdFp5T1fgjWdPSCf9cDqcCASMBgcLqjzzBvptjAfAxN"
  LISTEN         = "/ip6/::/tcp/8080/ws"
  ANNOUNCE       = "/dns4/canvas-chat-discovery-p0.fly.dev/tcp/443/wss"
  DEBUG          = "libp2p:*:error,canvas:*:error,canvas:gossipsub:*"
  RESTART_AT     = "07:00"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    handlers = ["http", "tls"]
    port = 443

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 8000

[metrics]
port = 8001
path = "/metrics"