app = "canvas-chat-discovery-staging-p1"
kill_signal = "SIGINT"
kill_timeout = 30
processes = []

[env]
  BOOTSTRAP_LIST = "/dns6/canvas-chat-discovery-staging-p0.internal/tcp/8080/ws/p2p/12D3KooWFtS485QGEZwquMQbq7MZTMxiuHs6xUKEi664i4yWUhWa /dns6/canvas-chat-discovery-staging-p2.internal/tcp/8080/ws/p2p/12D3KooWPix1mT8QavTjfiha3hWy85dQDgPb9VWaxRhY8Yq3cC7L"
  LISTEN         = "/ip6/::/tcp/8080/ws"
  ANNOUNCE       = "/dns4/canvas-chat-discovery-staging-p1.fly.dev/tcp/443/wss"
  DEBUG          = "libp2p:*:error,canvas:*:error,canvas:gossipsub:*"
  RESTART_AT     = "19:00"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[metrics]
port = 8000
path = "/metrics"