app = "test-discovery-p1"
kill_timeout = 10

[[vm]]
  memory = "2gb"

[env]
  BOOTSTRAP_LIST = "/dns6/test-discovery-p0.internal/tcp/8080/ws/p2p/12D3KooWSndvFSJtqq9NT4qQxB7jni6styhfuY4cZhdavq7daeJe /dns6/test-discovery-p2.internal/tcp/8080/ws/p2p/12D3KooWQFJcBXTT5LH2aGJzyYRPkBPd4WsqxccmLwpvn6DxLFdq"
  LISTEN         = "/ip6/::/tcp/8080/ws"
  ANNOUNCE       = "/dns4/test-discovery-p1.fly.dev/tcp/443/wss"
  DEBUG          = "libp2p:*:error,canvas:*:error"
  RESTART_AT     = "19:00"

# libp2p service
[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    handlers = ["http", "tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "10s"
    restart_limit = 0
    timeout = "2s"

# http stats server
[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 8000

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000

[metrics]
  port = 8000
  path = "/metrics"

[[restart]]
  policy = "always"
  processes = ["app"]