app = "canvas-chat-discovery-staging-p2"
kill_signal = "SIGINT"
kill_timeout = 30
processes = []

[env]
  BOOTSTRAP_LIST = "/dns6/canvas-chat-discovery-staging-p0.internal/tcp/8080/ws/p2p/12D3KooWFtS485QGEZwquMQbq7MZTMxiuHs6xUKEi664i4yWUhWa /dns6/canvas-chat-discovery-staging-p1.internal/tcp/8080/ws/p2p/12D3KooWRbxAWmpvc9U7q1ftBTd3bKa1iQ2rn6RkwRb1d9K7hVg5"
  LISTEN         = "/ip6/::/tcp/8080/ws"
  ANNOUNCE       = "/dns4/canvas-chat-discovery-staging-p2.fly.dev/tcp/443/wss"
  DEBUG          = "libp2p:*,canvas:*,libp2p:gossipsub:trace"
  RESTART_AT     = "00:30"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[metrics]
port = 8000
path = "/metrics"