app = "canvas-chat-2"
kill_signal = "SIGINT"
kill_timeout = 30
processes = []

[env]
  ANNOUNCE = "/dns4/canvas-chat-2.fly.dev/tcp/443/wss"
  DEBUG    = "canvas:*"

[mounts]
  destination = "/data"
  source = "data"

[[services]]
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[metrics]
  port = 8000
  path = "/metrics"
