name = "modeldb-durable-objects"
main = "test/worker.ts"
compatibility_date = "2024-09-25"

[durable_objects]
bindings = [
  { name = "TEST_OBJECT", class_name = "TestObject" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["TestObject"]
