app = 'canvas-testnet-rendezvous'
primary_region = 'ewr'
kill_signal = 'SIGINT'
kill_timeout = '30s'

[build]

[env]
PORT = '8000'
LISTEN = '/ip6/::/tcp/8080/ws'
ANNOUNCE = '/dns6/canvas-testnet-rendezvous.internal/tcp/8080/ws'
DASHBOARD_URL = 'http://canvas-testnet-dashboard.internal:8000'

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 2
