# fly.toml file generated for canvas-bootstrap-peer on 2022-10-04T02:00:31-04:00

app = "interwallet-server-p1"
primary_region = "bos"
kill_signal = "SIGINT"
kill_timeout = 30
processes = []

# [build]
#   builder = "heroku/buildpacks:20"

[env]
  # DATA_DIRECTORY = "/data"
  BOOTSTRAP_LIST = "/dns6/interwallet-server-p0.internal/tcp/8080/ws/p2p/12D3KooWGbcMSpZUGhSfD9pk2hTF8TFy5bZzsvh4B3hGPM3h344X"
  LISTEN         = "/ip6/::/tcp/8080/ws"
  ANNOUNCE       = "/dns4/interwallet-server-p1.fly.dev/tcp/443/wss"
  DEBUG          = "canvas:*"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  
[metrics]
port = 8000
path = "/metrics"